#!/usr/bin/env php
<?php

use hiqdev\composer\config\Builder;

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require_once $file;
        break;
    }
}

unset($file);

Builder::rebuild(Builder::findOutputDir(dirname(dirname(__DIR__))));
